config/routes.rb
Eshop::Application.routes.draw do

  get "categories/show"
  get "comments/index"
  get "comments/show"
  get "comments/new"
  get "comments/create"
  get "products/edit"
  get "products/new"
  get "products/destroy"
  get "products/index"
  get "products/show"

  resources :admin_sessions
  resources :posts, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:show]
  resources :products

  namespace :admin do
    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/kontakt" => "pages#contact", as: :contact

  root to: "posts#index"

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :category
	scope :published, -> { where(published: true) }

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
   
  layout "admin"
  before_action :require_admin_session

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post].permit(:title, :body, :published, :category_id)
  
    if @post.save
        redirect_to admin_posts_url
    else
        render :new
    end
  end

  def edit
    @post = Post.find params[:id]
    
  end

  def update
    @post = Post.find params[:id]
    if @post.update params[:post].permit(:title, :body, :published, :category_id)
        redirect_to admin_posts_url
    else
        render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
      redirect_to admin_posts_url
  end

  

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
   
   layout "admin"
   before_action :require_admin_session

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new params[:product].permit(:name, :description, :price, :image_url)
    
    if @product.save
    redirect_to admin_products_url
    
    else
      render :new
    end 
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    if @product.update params[:product].permit(:name, :description, :price, :image_url)
       redirect_to admin_products_url
    else
      render :edit
    end

  end

  def show
    @product = Product.find params[:id]
  end

  def destroy
  end
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController

layout "admin"

def new

end

def create
	if params[:email] == "janko@gmail.com" && params[:password] == "123"
		session[:logged] = true
		redirect_to admin_posts_url
	else
		flash[:alert] = "Nespravny email alebo heslo"
		render :new
	end

end

def destroy
	session[:logged] = nil
	flash[:alert] = "Bol si odhlaseny"
	redirect_to new_admin_session_url
end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def require_admin_session
    unless session[:logged]
    	flash[:alert] = "Pre vstup do adminu potrebujes byt prihlaseny"
      redirect_to new_admin_session_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def show
  	@category = Category.find params[:id]
  	@posts = @category.posts.published

  	@categories = Category.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  	@post = Post.find params[:post_id]
  	@comment = @post.comments.build comment_params
  	@comment.save
  	redirect_to post_url(@post)
  end

  private

  def comment_params
  	params[:comment].permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published
    @categories = Category.all
  end

  def show
    @post = Post.published.find params[:id]
    @comments = @post.comments
    @comment = Comment.new
  end
 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find params[:id]
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_item(name, path)
    content_tag 'li', class: (current_page?(path) ? 'active' : nil) do 
    	link_to name,path 
    end
  end

  def pluralize_sk(count, singular, plural_1, plural_2)
  	#count.to_s + "" + plural_1

  	case count
      when 0
      	"#{count} #{plural_1}"
  	  when 2..4
  	  	"#{count} #{plural_2}"
  	  when 1
  	  	"#{count} #{singular}"
  	  else
  	  	"#{count} #{plural_1}"
  	  end

  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, {prompt: "Vyber kategóriu"}, {class: "form-control"}  %>
  </div>

  <div class="form-group" data-no-turbolink>
  <%= f.label :body %>
  <%= f.text_area :body, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
  <%= f.check_box :published %>
  <%= f.label :published, class: "form-control" %>
  </div>
  
  <%= f.submit "Uložiť článok" %>

<% end %>

app/views/admin/posts/edit.html.erb
<h1>Upraviť článok</h1>

<%= render "form" %>

app/views/admin/posts/index.html.erb
<h1>Admin článkov</h1>

<%= link_to "Pridať článok", new_admin_post_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
  	<tr>
  	  <th>Názov</th>
      <th>Kategória</th>
  	  <th>Publikované</th>
  	  <th></th>

  	</tr>
  </thead>

  <tbody>
<% @posts.each do |post| %>
   
 <tr>
   <td><%= post.title %></td>
   <td><%= post.category.name if post.category %></td>
   <td><%= post.published %></td>
   <td><%= link_to "Upraviť", edit_admin_post_path(post), class: "btn btn-primary" %> | 
       <%= link_to "Zmazať", admin_post_path(post), method: "delete", confirm: "naozaj?", class: "btn btn-primary" %></td>
 </tr>
<% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h1>Vytvoriť nový článok</h1>


<%= render "form" %>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "ckeditor" %>
  </div>

  <div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price %>
  </div>

  <div class="form-group">
   <%= f.label :image_url %>
   <%= f.text_field :image_url %>
  </div>
  
  <%= f.submit "Uložiť produkt" %>

<% end %>

app/views/admin/products/destroy.html.erb
<h1>Admin::Products#destroy</h1>
<p>Find me in app/views/admin/products/destroy.html.erb</p>

app/views/admin/products/edit.html.erb
<h1>Uprava produktu</h1>
<p></p>
<%= render "form" %>

app/views/admin/products/index.html.erb
<h1>Produkty</h1>

<%= link_to "Pridať produkt", new_admin_product_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
  	<tr>
  	  <th>Meno</th>
  	  <th>Popis</th>
  	  <th>Cena</th>
  	  <th>Obrázok</th>
  	  <th></th>

  	</tr>
  </thead>

  <tbody>
<% @products.each do |product| %>
 <div class="row">  
 <tr>
   <td><strong><%= product.name %></strong></td>
   <td><%= product.description.html_safe %></td>
    <td><%= product.price %></td>
     <td><%= image_tag product.image_url, height: '200', width: '150' %></td>
   <td><%= link_to "Upraviť", edit_admin_product_path(product), class: "btn btn-primary" %> | 
       <%= link_to "Zmazať", admin_product_path(product), method: "delete", confirm: "naozaj?", class: "btn btn-primary" %></td>
 </tr>
<% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1>Vytvoriť nový produkt</h1>


<%= render "form" %>

app/views/admin/products/show.html.erb
<h1><%= @product.name %></h1>
<p>Find me in app/views/admin/products/show.html.erb</p>

app/views/posts/_post.html.erb
  <h3><%= link_to post.title, post_path(post) %></h3>

  <%= post.body.html_safe %>

app/views/posts/index.html.erb
<h1>Články</h1>
<p></p>

<% @posts.each do |post| %>
  <h3><%= link_to post.title, post_path(post) %></h3>

  <%= post.body.html_safe %>
<% end %>

app/views/posts/show.html.erb
<h1>Číslo článku: <%= @post.id %></h1>
<h3>Názov článku: <%= @post.title %></h3>
<p><%= @post.body.html_safe %></p>
<h2>Komentáre</h2>
<p> <%= pluralize_sk(@comments.count, "komentár", "komentárov", "komentáre") %></p>
<p></p>
<ul>
  <%= render @comments %>
</ul>



<h2>Pridať komentár</h2>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/products/_product.html.erb
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= product.name %></h3>
        <p> <%= image_tag product.image_url,height: '200', width: '150' %></p>
        <p><%= truncate product.description.html_safe, length: 100 %></p>
        <p><%= product.price %>,- EUR</p>
        <p><%= link_to "Ukáž", product_path(product), class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
<h1>Produkty</h1>
<div class="row product">
  <%= render @products %>
</div>

app/views/products/show.html.erb
<h1>Produkt číslo: <%= @product.id %></h1>
<h3>Názov produktu: <%= @product.name %></h3>
<p><%= image_tag @product.image_url %></p>
<p><%= @product.description.html_safe %></p>
<p></p>
<%= link_to "Späť", products_path, class: "btn btn-primary" %>