config/routes.rb
Eshop::Application.routes.draw do

  get "categories/show"
  get "comments/index"
  get "comments/show"
  get "comments/new"
  get "comments/create"
  get "products/edit"
  get "products/new"
  get "products/destroy"
  get "products/index"
  get "products/show"

  resources :admin_sessions
  resources :posts, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:show]
  resources :products

  namespace :admin do
    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/kontakt" => "pages#contact", as: :contact

  root to: "posts#index"

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :category
	scope :published, -> { where(published: true) }

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController

layout "admin"

def new

end

def create
	if params[:email] == "janko@gmail.com" && params[:password] == "123"
		session[:logged] = true
		redirect_to admin_posts_url
	else
		flash[:alert] = "Nespravny email alebo heslo"
		render :new
	end

end

def destroy
	session[:logged] = nil
	flash[:alert] = "Bol si odhlaseny"
	redirect_to new_admin_session_url
end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def require_admin_session
    unless session[:logged]
    	flash[:alert] = "Pre vstup do adminu potrebujes byt prihlaseny"
      redirect_to new_admin_session_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def show
  	@category = Category.find params[:id]
  	@posts = @category.posts.published

  	@categories = Category.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  	@post = Post.find params[:post_id]
  	@comment = @post.comments.build comment_params
  	@comment.save
  	redirect_to post_url(@post)
  end

  private

  def comment_params
  	params[:comment].permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published
    @categories = Category.all
  end

  def show
    @post = Post.published.find params[:id]
    @comments = @post.comments
    @comment = Comment.new
  end
 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find params[:id]
  end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_item(name, path)
    content_tag 'li', class: (current_page?(path) ? 'active' : nil) do 
    	link_to name,path 
    end
  end

  def pluralize_sk(count, singular, plural_1, plural_2)
  	#count.to_s + "" + plural_1

  	case count
      when 0
      	"#{count} #{plural_1}"
  	  when 2..4
  	  	"#{count} #{plural_2}"
  	  when 1
  	  	"#{count} #{singular}"
  	  else
  	  	"#{count} #{plural_1}"
  	  end

  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eshop</title>
  <META http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header_admin">
  <div class="container">
    <ul class="nav nav-pills">
      <li><%= nav_item "Home", "#" %></li>
      <li><%= nav_item "Blog", admin_posts_path %></li>
      <li><%= nav_item "Kontakt", "#" %></li>
      <li><%= nav_item "Produkty", admin_products_path %></li>
        <li><%= link_to "Späť na User web", products_path %></li>
        <li class="pull-right"><%= link_to "Odhlásiť sa", admin_session_path(1), method: :delete %></li>
      
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eshop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <ul class="nav nav-pills">
      <li><%= nav_item "Home", "#" %></li>
      <li><%= nav_item "Blog", posts_path %></li>
      <li><%= nav_item "Kontakt", contact_path %></li>
      <li><%= nav_item "Produkty", products_path %></li>
        <li><%= link_to "Admin", admin_products_path %></li>
    </ul>
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>